# Generated by Django 6.0.7 on 2026-08-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_niveau_remove_subject_category_matiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='niveau',
        ),
    ]
