# Generated by Django 5.2.4 on 2026-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plateforme', models.CharField(default='Plateforme pédagogique', max_length=255)),
                ('nom_etablissement', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('autoriser_inscriptions', models.BooleanField(default=True)),
                ('validation_documents', models.BooleanField(default=True)),
                ('autoriser_commentaires', models.BooleanField(default=True)),
                ('mode_maintenance', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres de la plateforme',
            },
        ),
    ]
