# Generated by Django 5.2.4 on 2026-08-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='mode_maintenance',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='nom_etablissement',
        ),
    ]
