# Generated by Django 5.2.4 on 2026-07-08 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_niveau_remove_subject_category_matiere_and_more'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='document',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='document',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.matiere', verbose_name='Matière'),
        ),
        migrations.AddField(
            model_name='document',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.niveau', verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(upload_to='resources/%Y/%m/', verbose_name='Fichier')),
                ('type_document', models.CharField(choices=[('cours', 'Cours'), ('exercice', 'Exercice'), ('fiche', 'Fiche pédagogique'), ('correction', 'Correction')], default='cours', max_length=20, verbose_name='Type de document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvée')),
                ('nb_telechargements', models.PositiveIntegerField(default=0, verbose_name='Téléchargements')),
                ('auteur', models.ForeignKey(db_column='auteur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('matiere', models.ForeignKey(db_column='matiere_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='categories.matiere', verbose_name='Matière')),
                ('niveau', models.ForeignKey(db_column='niveau_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='categories.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
    ]
