# Generated by Django 5.2.4 on 2026-07-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_tag_rename_commentaire_comment_document_tags_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='nb_telechargements',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
