# Generated by Django 5.2.4 on 2026-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_document_nb_telechargements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='nb_telechargements',
            field=models.PositiveIntegerField(default=0, verbose_name='Téléchargements'),
        ),
    ]
