# Generated by Django 5.2.4 on 2026-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_document_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
    ]
