# Generated by Django 5.2.4 on 2026-07-23 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_niveau_remove_subject_category_matiere_and_more'),
        ('resources', '0008_document_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='document',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='document',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='document',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.matiere', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='document',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.niveau', verbose_name='Niveau'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Ressource',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
