# Generated by Django 5.2.4 on 2026-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_remove_ressource_auteur_remove_ressource_matiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type_ressource',
            field=models.CharField(choices=[('cours', 'Cours'), ('exercices', 'Exercices'), ('fiche_pedagogique', 'Fiche pédagogique')], default='cours', max_length=20, verbose_name='Type de ressource'),
            preserve_default=False,
        ),
    ]
