# Generated by Django 6.0.7 on 2026-08-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_document_type_ressource'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
