# Generated by Django 6.0.7 on 2026-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_document_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
