# Generated by Django 6.0.7 on 2026-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_alter_document_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_ressource',
            field=models.CharField(choices=[('cours', 'Cours'), ('exercices', 'Exercices'), ('annales', 'Annales'), ('annales_sujet_corriges', 'Annales avec sujets et corrigés'), ('fiche_pedagogique', 'Fiche pédagogique')], max_length=30, verbose_name='Type de ressource'),
        ),
    ]
